version: '3.8'

services:
  afl:
    build: .
    container_name: afl
    privileged: true
    environment:
      - SLAVES=12
    volumes:
      - ./results:/root/results
      - ../testcases:/root/testcases
